apiVersion: v1
kind: ConfigMap
metadata: 
  name: pod-config
data:
  course: "DevSecOps with AWS"
  Trainer: "Sivakumar"
  "Duriation": "90 Days"

#Config map is used for non-confidential data,, for confidential data in kubernets we have kubernetes secret